const strings = {
    app:{
        about_description: 'This is awesome app make using reactjs.',
        about_sub_title: 'App to find Github users and see your informations ;)',
        about_title: 'About This App',
        helmet:'Github Find User',
        name: 'Github Find User',
        version: 'Version: ',
        version_number: '0.1.0',
    },
    comum:{
        about: 'About',
        clear: 'Clear',
        details: 'Details',
        go_back:'Go Back',
        home: 'Home',
        search:'Search',
        warning: 'Warning',
    },
    users : {
        blog: 'Blog',
        company: 'Company',
        created_at: 'Created at',
        email: 'Email',
        followers:'Followers',
        following: 'Following',
        github: 'Github',
        github_tooltip: 'Go to github profile',
        hireable: 'Hireable',
        id: 'Id',
        location: 'Location',
        login: 'Login',
        name: 'Name',
        node_id: 'Node Id',
        public_gist: 'Public Gist',
        public_repositories:'Public Repositories',
        repositorie_button: 'See public repositories',
        repositories: 'Repositories',
        score: 'Score',
        search_input_placeholder:'Input Github User...',
        search_input_warning: 'Need input a Github user name',
        starred_button:'See starred repositories',
        starreds: 'Starreds',
        type: 'Type',
        updated_at: 'Updated at',
        url: 'Url',
        watchers:'Watchers',
        forks: 'forks',
    },
    fallback_text: '---',
    not_found_page: `Sorry, we didn't find what you were looking for :(`
};

export default strings;
  