export const GET_USER = 'GET_USER';
export const CLEAR_USERS = 'CLEAR_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';

export const CLEAR_REPOSITORIES = 'CLEAR_REPOSITORIES';
export const GET_REPOSITORIES = 'GET_REPOSITORIES';

export const CLEAR_STARREDS = 'CLEAR_STARREDS';
export const GET_STARREDS = 'GET_STARREDS';

export const SET_LOADING = 'SET_LOADING';
